name: Firestore Backups

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Backup"
        default: "Backup"
        required: false
  schedule:
    - cron: "0 4 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
      - run: gcloud firestore export gs://${{ secrets.GCP_PROJECT_ID }}.appspot.com
